# Generated by Django 4.0.2 on 2022-02-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cidade',
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviso', models.TextField()),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.universidade')),
            ],
        ),
    ]
