# Generated by Django 4.0.2 on 2022-02-07 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_curso_bairro_remove_curso_cidade_aviso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='universidade',
        ),
        migrations.AddField(
            model_name='curso',
            name='aviso',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='home.aviso'),
            preserve_default=False,
        ),
    ]
