# Generated by Django 4.0.2 on 2022-02-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_curso_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='modalidade_1',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='modalidade_2',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='modalidade_3',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='turno_1',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='turno_2',
        ),
    ]
