# Generated by Django 4.0.2 on 2022-02-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_curso_modalidade_1_remove_curso_modalidade_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='desconto',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
