# Generated by Django 4.0.2 on 2022-02-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_curso_desconto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroBolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('nascimento', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.CharField(max_length=8, null=True)),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80, null=True)),
                ('universidade', models.CharField(max_length=80)),
            ],
        ),
    ]
