# Generated by Django 4.0.2 on 2022-02-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cadastrobolsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrobolsa',
            name='curso',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastrobolsa',
            name='universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.universidade'),
        ),
    ]
